import sys
import pandas as pd
import logging
from pathlib import Path
from datetime import datetime

# Add project root to path
sys.path.append(str(Path(__file__).resolve().parent.parent))

from prop_analyzer import config as cfg
from prop_analyzer.config import Cols
from prop_analyzer.utils import common

def main():
    common.setup_logging(name="update_db")
    logging.info(">>> STARTING DATABASE UPDATE (Results Integration) <<<")
    
    # 1. Load the Graded Results (Yesterday's Picks)
    # This file is generated by run_grading.py
    graded_file = cfg.GRADED_DIR / f"graded_{datetime.now().strftime('%Y-%m-%d')}.csv"
    
    # If not found today, try looking for the most recent one
    if not graded_file.exists():
        files = sorted(cfg.GRADED_DIR.glob("graded_*.csv"), reverse=True)
        if files:
            graded_file = files[0]
            logging.info(f"Today's graded file not found. Using latest: {graded_file.name}")
        else:
            logging.critical("No graded result files found. Run 'run_grading.py' first.")
            return

    try:
        results_df = pd.read_csv(graded_file)
        if results_df.empty:
            logging.warning("Graded results file is empty.")
            return
            
        logging.info(f"Loaded {len(results_df)} graded results from {graded_file.name}")
        
    except Exception as e:
        logging.critical(f"Failed to read graded results: {e}")
        return

    # 2. Load Master Training Dataset (The Target)
    train_path = cfg.MASTER_TRAINING_FILE
    if not train_path.exists():
        logging.critical(f"Master training dataset not found at {train_path}")
        return
        
    try:
        train_df = pd.read_parquet(train_path)
        logging.info(f"Loaded Master Dataset: {len(train_df)} rows")
    except Exception as e:
        logging.critical(f"Failed to read master dataset: {e}")
        return

    # 3. Validation & Merging
    # We want to add the 'Actual Value' and 'Result' to the training set if they are missing
    
    # Ensure ID/Date format matches
    if Cols.DATE in results_df.columns:
        results_df[Cols.DATE] = pd.to_datetime(results_df[Cols.DATE]).dt.normalize()
    if Cols.DATE in train_df.columns:
        train_df[Cols.DATE] = pd.to_datetime(train_df[Cols.DATE]).dt.normalize()
        
    # We only care about rows where we have a result
    valid_results = results_df.dropna(subset=[Cols.ACTUAL_VAL])
    
    if valid_results.empty:
        logging.warning("No valid results (Actual Value) found in graded file.")
        return

    # Create a composite key for matching
    # (Player + Date + PropType) helps us find the exact row
    # Note: Training set usually has one row per game, but features are specific to the prop type.
    # However, our training set structure is traditionally Player-Game rows.
    # The 'Actual Value' depends on the column (e.g. PTS vs REB).
    
    # STRATEGY: 
    # Since we rebuilt the dataset using `dataset.py` (which pulls from official box scores),
    # the "Actual Values" should ALREADY be in the master dataset if you ran `run_build_db.py`.
    #
    # `run_update_db.py` is mostly useful if you are manually tracking results or using 
    # specific lines/odds that aren't in the box score (like the closing line).
    
    # For this architecture, running `run_build_db.py` is actually the correct way 
    # to "update" the database with new stats.
    # `run_update_db.py` is arguably redundant now that `dataset.py` is automated.
    
    logging.info("NOTE: With the new Parquet pipeline, `run_build_db.py` automatically imports")
    logging.info("the latest box scores and updates the training history.")
    logging.info("This script will verify data integrity instead.")
    
    # Data Integrity Check
    merged = pd.merge(
        valid_results, 
        train_df[[Cols.PLAYER_ID, Cols.DATE]], 
        on=[Cols.PLAYER_ID, Cols.DATE], 
        how='inner'
    )
    
    logging.info(f"Verified {len(merged)} records from recent results exist in Master Dataset.")
    
    if len(merged) < len(valid_results):
        missing = len(valid_results) - len(merged)
        logging.warning(f"{missing} records from Graded Results are MISSING from Master Dataset.")
        logging.warning("Recommendation: Run 'python scripts/run_build_db.py' to refresh the master dataset.")
    else:
        logging.info("Database is fully synchronized.")

    logging.info("<<< UPDATE COMPLETE >>>")

if __name__ == "__main__":
    main()